server:
  port: 9007
  forward-headers-strategy: framework

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/notification_db?maxPoolSize=50&minPoolSize=10&maxIdleTimeMS=300000&waitQueueTimeoutMS=10000}
      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.hust-elearning.online/realms/elearning-realm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://keycloak:8080/realms/elearning-realm/protocol/openid-connect/certs}

  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:takitori.dev@gmail.com}
    password: ${MAIL_PASSWORD:jaju dbbz azlf szyh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:kafka:29092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.hust.commonlibrary.event"

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.hust.notificationservice: DEBUG
    org.springframework.security: INFO

app:
  frontend-url: ${FRONTEND_URL:https://app.hust-elearning.online}
  backend-url: ${BACKEND_URL:https://api.hust-elearning.online}
